### ISSUE TITLE
Failover Instructions

### ISSUE THREAD

**Issue by martinduke** [martinduke/draft-duke-quic-load-balancers#24]
Subodh wanted a failover mode if QUIC-LB configuration was somehow unavailable. This is a special type of CID that instructs the load balancer to just use the 4-tuple. As we have 4 cod e points for config rotation, we thought we could use one of them to represent this mode.

**Comment by nibanks** [comment]
Should the default configuration of all servers assume simple 2/4-tuple UDP load balancing and disable migration?

**Comment by martinduke** [comment]
That is the essence of it. If configured to expect an LB and it doesn't get one, simply pick any CID with the rotation bits set to the correct endpoint, and disable migration.

LBs that see the rotation codepoint just use the 5-tuple
