### ISSUE TITLE
Add text about NATting

### ISSUE THREAD

**Issue by martinduke** [martinduke/draft-duke-quic-load-balancers#55]
Via @dtikhonov: Some load balancers might also serve as NATs, in which case they have some per-connection state. 

If this state is per-fourtuple, all the QUIC address change mechanisms will work fine. We should add some text to the security considerations that doing this on a connection ID basis (trying to be QUIC-aware) is actually worse -- it can lead to masking address changes from the server and prevent employment of path verification mechanisms.

**Comment by kazuho** [comment]
SGTM. It might be a good idea to have a note about the possibility, because IIRC a server is permitted to skip address validation when the client port changes but the IP address continues to be the same.

**Comment by martinduke** [comment]
I also filed  https://github.com/quicwg/ops-drafts/issues/87 because this
is a general problem for NATs that are getting too cute with CIDs. I might
end up putting some text in the manageability draft and just pointing to
that in QUIC-LB.

**Comment by martinduke** [comment]
Addressed in both ops draft and draft-duke-quic-natsupp-00.
