### ISSUE TITLE
Misrouted/delayed ACK break the protocol

### ISSUE THREAD

**Issue by dtikhonov** [martinduke/draft-duke-quic-load-balancers#56]
(Copied from [the original report in Google groups](https://groups.google.com/d/msg/quic-load-balancers/zB_fhAaarn0/MtRKuGoIAwAJ).)

[Section 7.2](https://tools.ietf.org/html/draft-duke-quic-load-balancers-06#section-7.2) states:

> The QUIC-LB load balancers send the encoding parameters to servers and periodically retransmit until that server responds with an acknowledgement.  Specifics of this retransmission are implementation-dependent.

IIUC, this means that the following scenario can occur:

```
    LB: send M1
                            Server: receive M1
                            Server: send ACK1 (gets routed to loopy land)
    LB: send M1 again
                            Server: receive M1
                            Server: send ACK2
    LB: receive ACK2
    LB: send M2 (gets lost)
    LB: receive ACK1 (after some odd wandering it's back again)
    LB: stop retransmitting M2
```

This can probably be solved by adding a simple epoch-like counter to the packets.

**Comment by martinduke** [comment]
Obviated by deleting the protocol.
