### ISSUE TITLE
We may not be able to use a fifth packet type

### ISSUE THREAD

**Issue by martinduke** [martinduke/draft-duke-quic-load-balancers#9]
Martin Thomson's new first byte proposal would eliminate any extra QUIC long header codepoints that we are currently using for QUIC-LB.

This is not yet final, but are there other mechanisms we could use? One would be to use the RETRY type: if a server receives one, it must be QUIC_LB. A load balancer would probably be able to disambiguate this as well. But it is kind of gross.

**Comment by nibanks** [comment]
I'd rather argue to get a packet type reserved in the transport spec. I don't like reusing the Retry packet. It is an acceptable last option though.

**Comment by nibanks** [comment]
Should we open an issue on the transport doc to request a packet type to be reserved?

**Comment by martinduke** [comment]
I emailed Martin T. for guidance about how to proceed.

**Comment by nibanks** [comment]
Any more updates on this?

**Comment by martinduke** [comment]
M.T. was inclined to just have us use some of the non-QUIC codepoint space in the first byte. As the change to QUIC hasn't landed I think we can leave this as a placeholder for now.

**Comment by dtikhonov** [comment]
The idea is to make QUIC-LB packets look like QUIC. It would be a pity to lose this useful property.

**Comment by martinduke** [comment]
I am keeping this issue open but will not press it until MT lands his redo of the first byte. If anyone else wants to nag him at a meeting, be my guest.

**Comment by nibanks** [comment]
I agree. I think we should explicitly open an issue on the transport now. I see the following as possible changes to the transport draft:

- Explicitly define a generic QUIC-LB packet type but defines no message types.
- Just reserve a value (or range of values) that we can then use.

I prefer the second one so we don't have to finalize any of the QUIC-LB formatting immediately for the transport spec. I believe if this issue is opened, and enough of the LB folks chime in and +1 it, it probably would get accepted.

**Comment by martinduke** [comment]
Sure, let's file an issue for a reserved codepoint. Until adoption I don't think we can do much more than that.

**Comment by martinduke** [comment]
Sounds like M.T.'s first-byte rearrangement is going to happen. Can someone file the issue vs. quic-transport.

**Comment by nibanks** [comment]
Done: https://github.com/quicwg/base-drafts/issues/1980

**Comment by nibanks** [comment]
As discussed in the base-drafts Issue, we will have to use a different version number for QUIC-LB instead. I don't think that will be a big deal. I can write up a PR sometime this week most likely.
